openapi: 3.0.3
info:
  title: DRF Quiz Project
  version: 1.0.0
  description: Quiz DRF Project
paths:
  /answers/:
    get:
      operationId: answers_list
      description: Этот эндпоинт возвращает ответы квиза
      tags:
      - answers
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Answer'
          description: ''
  /articles/:
    get:
      operationId: articles_list
      description: Этот эндпоинт возвращает все статьи
      parameters:
      - in: query
        name: category__name
        schema:
          type: string
      - in: query
        name: content__icontains
        schema:
          type: string
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: page_size
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      - in: query
        name: title__icontains
        schema:
          type: string
      tags:
      - articles
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedArticleList'
          description: ''
  /articles/int:pk/:
    get:
      operationId: articles_int:pk_list
      description: Этот эндпоинт возвращает все статьи
      parameters:
      - in: query
        name: category__name
        schema:
          type: string
      - in: query
        name: content__icontains
        schema:
          type: string
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: page_size
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      - in: query
        name: title__icontains
        schema:
          type: string
      tags:
      - articles
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedArticleList'
          description: ''
  /categories/:
    get:
      operationId: categories_list
      description: Этот эндпоинт возвращает категории
      tags:
      - categories
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
          description: ''
  /questions/:
    get:
      operationId: questions_list
      description: Этот эндпоинт возвращает вопросы квиза
      tags:
      - questions
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Question'
          description: ''
  /quiz/:
    get:
      operationId: quiz_list
      description: Этот эндпоинт возвращает все квизы
      parameters:
      - in: query
        name: category__name
        schema:
          type: string
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: page_size
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      - in: query
        name: title__icontains
        schema:
          type: string
      tags:
      - quiz
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedWelcomeList'
          description: ''
  /quiz-w/{id}/:
    get:
      operationId: quiz_w_retrieve
      description: Этот эндпоинт приветствие квиза
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - quiz-w
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Welcome'
          description: ''
  /quiz/{id}/:
    get:
      operationId: quiz_retrieve
      description: Этот эндпоинт возвращает определенный квиз
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - quiz
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quiz'
          description: ''
  /schema/:
    get:
      operationId: schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - schema
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
components:
  schemas:
    Answer:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        answer_text:
          type: string
          maxLength: 255
        is_right:
          type: boolean
      required:
      - answer_text
      - id
    Article:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 200
        category:
          $ref: '#/components/schemas/Category'
        read_time:
          type: integer
        art_image:
          type: string
          format: uri
          nullable: true
      required:
      - category
      - id
      - title
    Category:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
      required:
      - id
      - name
    PaginatedArticleList:
      type: object
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/Article'
    PaginatedWelcomeList:
      type: object
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/Welcome'
    Question:
      type: object
      properties:
        quiz:
          allOf:
          - $ref: '#/components/schemas/Quiz'
          readOnly: true
        title:
          type: string
          maxLength: 255
        answer:
          type: array
          items:
            $ref: '#/components/schemas/Answer'
          readOnly: true
      required:
      - answer
      - quiz
      - title
    Quiz:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          title: Quiz Title
          maxLength: 255
        category:
          type: integer
        quiz_image:
          type: string
          format: uri
          nullable: true
        question_count:
          type: integer
          readOnly: true
      required:
      - id
      - question_count
    Welcome:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        quiz_image:
          type: string
          format: uri
          nullable: true
        title:
          type: string
          title: Quiz Title
          maxLength: 255
        welcome_page:
          type: string
      required:
      - id
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
